name: road_runner_driver
description: The Driver App to Road Runner

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  states
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  #UI
  cupertino_icons: ^1.0.2
  another_flushbar: ^1.10.29
  argon_buttons_flutter: ^1.1.0
  push_notification: ^1.1.1
  otp_autofill: ^2.1.0
  swipe_refresh: ^1.0.2
  timelines: ^0.1.0
  rolling_switch: ^0.0.2
  charts_flutter: ^0.12.0
  flutter_native_splash: ^2.2.6
  flutter_svg: ^1.1.1+1
  adaptive_theme: ^3.1.1
  smooth_page_indicator: ^1.0.0+2
  dotted_border: ^2.0.0+2
  flutter_rating_bar: ^4.0.1
  swipeable_tile: ^2.0.0+1


  #networking
  geolocator: ^9.0.1
  flutter_osm_plugin: ^0.37.2+2
  dio: ^4.0.6
  #utilities
  image_picker: ^0.8.5+3
  file_picker: ^5.0.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  google_fonts: ^3.0.1
  image_cropper: ^2.0.3
  json_annotation: ^4.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  mobx_codegen: ^2.0.7
  flutter_launcher_icons: ^0.9.3
flutter_icons:
  android: "launcher_icon"
  ios: trueicon.jpeg
  image_path: "assets/brand/icon.jpeg"


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/illustrations/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
